version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql_practice
    ports:
      - "8085:3306"
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9908
      MYSQL_DATABASE: walkingMermaid
    volumes:
      - mysql_data:/var/lib/mysql  # Docker-managed volume

volumes:
  mysql_data:
